security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true

            logout:
                path: app_logout

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
