security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true

            logout:
                path: app_logout

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    access_control:
        - { path: '^/back-office-snowtricks', roles: ROLE_ADMIN }

#    role_hierarchy:
#        ROLE_USER: ROLE_USER
#        ROLE_ADMIN: ROLE_ADMIN
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]