<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Validation;


class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('title', textType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Attention, vous devez ajouter un titre'
                    ]),
                    new Length([
                        'min' => 2,
                        'max' => 255,
                        'minMessage' => 'Attention, le titre doit contenir au moins 2 caractères',
                        'maxMessage' => 'Attention, le titre doit contenir au maximum 255 caractères'
                    ])
                ],
                'label' => 'Titre',
                'empty_data' => ''
            ])
            ->add('content', textAreaType::class)
            ->add('status', choiceType:: class, [
                'choices' => [
                    'Publier' => 1,
                    'Brouillon' => 0
                ],
            ])
            ->add('user_id', hiddenType::class)
            ->add('image_id', integerType::class)
            ->add('Category', choiceType::class, [
                'choices' => [
                    'Grabs' => 'grabs',
                    'Rotations' => 'rotations',
                    'Flips' => 'flips',
                    'Rotations desaxées' => 'rotations_desaxees',
                    'Slides' => 'slides',
                    'One foot tricks' => 'one_foot',
                    'Old school' => 'old'
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'add_class' => Post::class,
        ]);
    }
}